name: Tech News On Grid
favicon: null
layout_spectrum: 0.851666750619188
typography_spectrum: 0.4656314942985773
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#A690A4'
    - '#B68F9D'
    - '#C8ACAB'
    - '#FBB9BF'
    - '#E376B7'
  brandStrength: 0.54732755292207
  lightness: 0.2625998882576823
  saturation: 0.43228882644325495
  rhythmicContrast: 0.1529560333583504
purpose: []
