name: Tech News On Grid
favicon: null
layout_spectrum: 0.72998
typography_spectrum: 0.63251
title: Tech News On Grid
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#0186d1'
    - '#7eb2e1'
    - '#e3e8ec'
    - '#012942'
    - '#8a8a1a'
  brandStrength: 0.0625
  lightness: 0.5
  saturation: 0.875
  rhythmicContrast: 0.5
purpose: []
